### ISSUE TITLE
Error when running fixer

### ISSUE THREAD

**Issue by DoctorWolfenstein** [Intothisworld/Redump-Dat-MIA-Fixer#1]
When running the fixer against a folder containing several dats, or just a single dat file, the error below is displayed. This is on Windows 10 Pro 22H2 and Python 3.11.8 with 'BeautifulSoup' and 'lxml' installed. Any ideas? Thanks in advance!

```
**Checking...
3 DAT files detected.

**Accessing online MIA Lists...

Traceback (most recent call last):
  File "C:\Scripts\Redump Dat MIA-Fixer v1.0.py", line 173, in <module>
    li_tags_list = soup_section.parent.next_sibling.next_sibling.select('li')
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'parent'
```

**Comment by intothisworld** [comment]
Ah okay, thanks for letting me know. Looks like the id for one of the MIA list headings in the wiki got changed at some point. I fixed it and it should work again now. I also removed the prompt asking about adding "[MIA]" to the beginning of the filenames. No one liked that option anyway, so will save you a keystroke now. =)

**Comment by DoctorWolfenstein** [comment]
All working great now, thank you!
